[tool.poetry]
name = "social-media-marketing"
version = "0.1.0"
description = ""
authors = ["Ethan <elavis00@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
